feat(docs): window size for locreg detrending
neuropsychology/NeuroKit pull request #747
Opened 2022-11-14 02:01 UTC by vasileermicioi

New PR as a follow-up of the discussion here https://github.com/neuropsychology/NeuroKit/pull/734

2022-11-14 02:35 UTC, DominiqueMakowski commented on neurokit2/signal/signal_detrend.py
> +        sample rate divided by the desired low-frequency band to remove
```suggestion
        sampling rate divided by the desired low-frequency band to remove 
```

2022-11-14 04:16 UTC, danibene requested changes
I think we shouldn't multiply `window` or `stepsize` by the sample rate because that's already done within the function

2022-11-14 04:16 UTC, danibene commented on neurokit2/signal/signal_detrend.py
> +        (``window = sample_rate / detrend_frequency``).
```suggestion
        (``window = 1 / detrend_frequency``)
```

2022-11-14 04:16 UTC, danibene commented on neurokit2/signal/signal_detrend.py
> +        sampling rate divided by the desired low-frequency band to remove
```suggestion
        1 divided by the desired low-frequency band to remove
```

2022-11-14 04:16 UTC, danibene commented on neurokit2/signal/signal_detrend.py
> +        For instance, to remove frequencies below ``0.67Hz`` the window should be ``1500``
```suggestion
        For instance, to remove frequencies below ``0.67Hz`` the window should be ``1.5``
```

2022-11-14 04:16 UTC, danibene commented on neurokit2/signal/signal_detrend.py
> +        (``1000 / 0.67 = 1500``).
```suggestion
        (``1 / 0.67 = 1.5``).
```

2022-11-14 04:16 UTC, danibene commented on studies/ecg_benchmark/README.md
> +                            window=sampling_rate/0.5,
```suggestion
                            window=1/0.5,
```

2022-11-14 04:16 UTC, danibene commented on studies/ecg_benchmark/make_data.py
> +#                            window=sampling_rate/0.5,
```suggestion
#                            window=1/0.5,
```

2022-11-14 04:16 UTC, danibene commented on studies/ecg_benchmark/make_data.py
>  #                            stepsize=0.02*sampling_rate)
```suggestion
#                            stepsize=0.02)
```

2022-11-14 04:16 UTC, danibene commented on studies/ecg_benchmark/README.md
>                              stepsize=0.02*sampling_rate)
```suggestion
                            stepsize=0.02)
```

2022-11-14 07:47 UTC, vasileermicioi commented
if I don't multiply by sampling_rate I get an error `'stepsize' should be more than 1. Increase its value`

`nk.signal_detrend(sig, method="locreg", window=0.5, stepsize=0.1)`

`nk.__version__` is 0.2.1

2022-11-14 13:24 UTC, danibene commented
> if I don't multiply by sampling_rate I get an error `'stepsize' should be more than 1. Increase its value`
> 
> `nk.signal_detrend(sig, method="locreg", window=0.5, stepsize=0.1)`
> 
> `nk.__version__` is 0.2.1

@vasileermicioi have you tried with the dev branch? That the sampling rate is multiplied within the function is a new change since 0.2.1

2022-11-15 01:30 UTC, DominiqueMakowski commented
@danibene perhaps if it's easier (instead of having @vasileermicioi fiddling with the branches) you can commit the edits and merge?

2022-11-15 03:03 UTC, merged